/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppPlannerRouteImport } from './routes/app.planner'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppInventoryRouteImport } from './routes/app.inventory'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppDonationsRouteImport } from './routes/app.donations'
import { Route as AppDashboardRouteImport } from './routes/app.dashboard'
import { Route as AppCommunityRouteImport } from './routes/app.community'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppCommunitySavedRouteImport } from './routes/app.community.saved'
import { Route as AppCommunityNearbyRouteImport } from './routes/app.community.nearby'
import { Route as AppCommunityDonationMapRouteImport } from './routes/app.community.donation-map'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryRoute = AppInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppDonationsRoute = AppDonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunityRoute = AppCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunitySavedRoute = AppCommunitySavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => AppCommunityRoute,
} as any)
const AppCommunityNearbyRoute = AppCommunityNearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => AppCommunityRoute,
} as any)
const AppCommunityDonationMapRoute = AppCommunityDonationMapRouteImport.update({
  id: '/donation-map',
  path: '/donation-map',
  getParentRoute: () => AppCommunityRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/community': typeof AppCommunityRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/donations': typeof AppDonationsRoute
  '/app/help': typeof AppHelpRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/community/donation-map': typeof AppCommunityDonationMapRoute
  '/app/community/nearby': typeof AppCommunityNearbyRoute
  '/app/community/saved': typeof AppCommunitySavedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/community': typeof AppCommunityRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/donations': typeof AppDonationsRoute
  '/app/help': typeof AppHelpRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/app/community/donation-map': typeof AppCommunityDonationMapRoute
  '/app/community/nearby': typeof AppCommunityNearbyRoute
  '/app/community/saved': typeof AppCommunitySavedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/community': typeof AppCommunityRouteWithChildren
  '/app/dashboard': typeof AppDashboardRoute
  '/app/donations': typeof AppDonationsRoute
  '/app/help': typeof AppHelpRoute
  '/app/inventory': typeof AppInventoryRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/planner': typeof AppPlannerRoute
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/app/community/donation-map': typeof AppCommunityDonationMapRoute
  '/app/community/nearby': typeof AppCommunityNearbyRoute
  '/app/community/saved': typeof AppCommunitySavedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/app/analytics'
    | '/app/community'
    | '/app/dashboard'
    | '/app/donations'
    | '/app/help'
    | '/app/inventory'
    | '/app/notifications'
    | '/app/planner'
    | '/app/profile'
    | '/app/settings'
    | '/app/'
    | '/app/community/donation-map'
    | '/app/community/nearby'
    | '/app/community/saved'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/app/analytics'
    | '/app/community'
    | '/app/dashboard'
    | '/app/donations'
    | '/app/help'
    | '/app/inventory'
    | '/app/notifications'
    | '/app/planner'
    | '/app/profile'
    | '/app/settings'
    | '/app'
    | '/app/community/donation-map'
    | '/app/community/nearby'
    | '/app/community/saved'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/app/analytics'
    | '/app/community'
    | '/app/dashboard'
    | '/app/donations'
    | '/app/help'
    | '/app/inventory'
    | '/app/notifications'
    | '/app/planner'
    | '/app/profile'
    | '/app/settings'
    | '/app/'
    | '/app/community/donation-map'
    | '/app/community/nearby'
    | '/app/community/saved'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/planner': {
      id: '/app/planner'
      path: '/planner'
      fullPath: '/app/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inventory': {
      id: '/app/inventory'
      path: '/inventory'
      fullPath: '/app/inventory'
      preLoaderRoute: typeof AppInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/donations': {
      id: '/app/donations'
      path: '/donations'
      fullPath: '/app/donations'
      preLoaderRoute: typeof AppDonationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community': {
      id: '/app/community'
      path: '/community'
      fullPath: '/app/community'
      preLoaderRoute: typeof AppCommunityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/community/saved': {
      id: '/app/community/saved'
      path: '/saved'
      fullPath: '/app/community/saved'
      preLoaderRoute: typeof AppCommunitySavedRouteImport
      parentRoute: typeof AppCommunityRoute
    }
    '/app/community/nearby': {
      id: '/app/community/nearby'
      path: '/nearby'
      fullPath: '/app/community/nearby'
      preLoaderRoute: typeof AppCommunityNearbyRouteImport
      parentRoute: typeof AppCommunityRoute
    }
    '/app/community/donation-map': {
      id: '/app/community/donation-map'
      path: '/donation-map'
      fullPath: '/app/community/donation-map'
      preLoaderRoute: typeof AppCommunityDonationMapRouteImport
      parentRoute: typeof AppCommunityRoute
    }
  }
}

interface AppCommunityRouteChildren {
  AppCommunityDonationMapRoute: typeof AppCommunityDonationMapRoute
  AppCommunityNearbyRoute: typeof AppCommunityNearbyRoute
  AppCommunitySavedRoute: typeof AppCommunitySavedRoute
}

const AppCommunityRouteChildren: AppCommunityRouteChildren = {
  AppCommunityDonationMapRoute: AppCommunityDonationMapRoute,
  AppCommunityNearbyRoute: AppCommunityNearbyRoute,
  AppCommunitySavedRoute: AppCommunitySavedRoute,
}

const AppCommunityRouteWithChildren = AppCommunityRoute._addFileChildren(
  AppCommunityRouteChildren,
)

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCommunityRoute: typeof AppCommunityRouteWithChildren
  AppDashboardRoute: typeof AppDashboardRoute
  AppDonationsRoute: typeof AppDonationsRoute
  AppHelpRoute: typeof AppHelpRoute
  AppInventoryRoute: typeof AppInventoryRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCommunityRoute: AppCommunityRouteWithChildren,
  AppDashboardRoute: AppDashboardRoute,
  AppDonationsRoute: AppDonationsRoute,
  AppHelpRoute: AppHelpRoute,
  AppInventoryRoute: AppInventoryRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
